name: flutter_group_project
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'  # Updated to a more recent SDK version

dependencies:
  firebase_database: ^11.0.2
  firebase_core: ^3.1.1
  cloud_firestore: ^5.0.2
  firebase_storage: ^12.1.0
  firebase_auth: ^5.1.1
  google_sign_in: ^6.2.1
  get: ^4.6.6
  cached_network_image: ^3.3.1
  image_picker: ^1.1.2
  emoji_picker_flutter: ^2.2.0
  firebase_messaging: ^15.0.0
  googleapis_auth: ^1.6.0
  http: ^1.1.0  # Adjusted to a more recent version
  flutter_notification_channel: ^3.1.0
  image_gallery_saver: ^2.0.3
  gallery_saver_updated: ^3.0.0
  flutter_lints: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.9
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/



flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/blue.png"
  # Ensure the above image_path points to a valid image asset in your project
  min_sdk_android: 19

#dependency_overrides:
 #####ref: ff72f00f142f13d889d7549e013af91cb0b523ab  # Replace with a valid commit hash


