// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhiGOzmk-uP4a3aZhKO941tGDvrekvxgA',
    appId: '1:401514346391:web:afe190d92fba8ed1e836d2',
    messagingSenderId: '401514346391',
    projectId: 'asap-messaging-app',
    authDomain: 'asap-messaging-app.firebaseapp.com',
    storageBucket: 'asap-messaging-app.appspot.com',
    measurementId: 'G-9ZDBRQW73N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCGO-8v3oKlgEKwduL3DqYl0Sq9Jj3LQw',
    appId: '1:401514346391:android:93209fa5c4a7ca72e836d2',
    messagingSenderId: '401514346391',
    projectId: 'asap-messaging-app',
    storageBucket: 'asap-messaging-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCY8CTZqK1axzps-UPcrB9dx2ddpuQjj7s',
    appId: '1:401514346391:ios:9f452c2334c86df9e836d2',
    messagingSenderId: '401514346391',
    projectId: 'asap-messaging-app',
    storageBucket: 'asap-messaging-app.appspot.com',
    androidClientId: '401514346391-0813u3r2tf0r7jaffqp7sbs0i08lukg0.apps.googleusercontent.com',
    iosClientId: '401514346391-jqa4jkd2352c6v8v8799tnunpa6to1ug.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterGroupProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCY8CTZqK1axzps-UPcrB9dx2ddpuQjj7s',
    appId: '1:401514346391:ios:9f452c2334c86df9e836d2',
    messagingSenderId: '401514346391',
    projectId: 'asap-messaging-app',
    storageBucket: 'asap-messaging-app.appspot.com',
    androidClientId: '401514346391-0813u3r2tf0r7jaffqp7sbs0i08lukg0.apps.googleusercontent.com',
    iosClientId: '401514346391-jqa4jkd2352c6v8v8799tnunpa6to1ug.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterGroupProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhiGOzmk-uP4a3aZhKO941tGDvrekvxgA',
    appId: '1:401514346391:web:f62cba4e8c477d51e836d2',
    messagingSenderId: '401514346391',
    projectId: 'asap-messaging-app',
    authDomain: 'asap-messaging-app.firebaseapp.com',
    storageBucket: 'asap-messaging-app.appspot.com',
    measurementId: 'G-H0WT5JSLV7',
  );
}